services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=patientsDB'
      - 'MONGO_INITDB_ROOT_PASSWORD=mwashi'
      - 'MONGO_INITDB_ROOT_USERNAME=mwale'
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
